# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xWBtDHdM4WBLyN7AXUi1RkZi3rSls486
"""

from google.colab import files
files.upload()

from google.colab import files
files.upload()

import numpy as np
import pandas as pd
import os

def generate_synthetic_ffr(n_samples=400, seed=42, mode='diameter'):
    """
    Generates synthetic FFR data based on hemodynamic physics.

    Parameters:
    - n_samples: Number of virtual patients
    - mode: 'diameter' (Real/Reference) or 'area' (Biased/Fake)
    """
    np.random.seed(seed)

    # 1. Generate Virtual Patient Geometries
    angles = np.random.choice([30, 45, 60, 90], n_samples)
    stenosis_ids = np.random.randint(1, 100, n_samples)

    # 2. Hemodynamic Modeling
    # FFR = 1 - (DeltaP / Pa)
    # DeltaP = C_lesion * (Stenosis^2) + C_vessel

    # Base stenosis severity (0.2 to 0.9)
    severity = np.random.uniform(0.2, 0.9, n_samples)

    if mode == 'diameter':
        # Realistic physics: Pressure drop is sensitive to diameter reduction
        pressure_drop = 0.5 * (severity**3.5) + 0.1 * (angles/90)
        ffr = 1.0 - pressure_drop
        # Add physiological noise
        ffr += np.random.normal(0, 0.02, n_samples)
    else:
        # Biased physics: Area-based assumptions underestimate pressure drop
        # This creates the "High FFR" bias seen in the fake dataset
        pressure_drop = 0.1 * (severity**2.0) + 0.02 * (angles/90)
        ffr = 1.0 - pressure_drop
        # Less variance in biased models
        ffr += np.random.normal(0, 0.01, n_samples)

    # 3. Final Constraints
    ffr = np.clip(ffr, 0.40, 1.0)

    # 4. Create DataFrame
    case_names = [f"A{a}_S{s:04d}" for a, s in zip(angles, stenosis_ids)]
    df = pd.DataFrame({
        'case_name': case_names,
        'FFR': ffr
    })

    return df

if __name__ == "__main__":
    print("Generating Reference (Diameter-based) Dataset...")
    df_real = generate_synthetic_ffr(mode='diameter', seed=42)
    df_real.to_csv('ref_diameter_ffr_benchmark.csv', index=False)

    print("Generating Biased (Area-based) Dataset...")
    df_fake = generate_synthetic_ffr(mode='area', seed=99) # Different seed for OOD
    df_fake.to_csv('biased_area_ffr_testset.csv', index=False)

    print("Done! Datasets generated successfully.")

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
import os

# 1. Configuration

class Config:
    LATENT_DIM = 16
    CONDITION_DIM = 2
    HIDDEN_DIM = 64
    BATCH_SIZE = 32
    LR = 0.0002
    BETA1 = 0.5
    EPOCHS = 200
    DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    FFR_MIN = 0.40


# 2. Data Processing

def parse_case_name(case_name):
    try:
        case_str = str(case_name)
        parts = case_str.split('_')
        angle = float(parts[0][1:])
        stenosis = float(parts[1][1:])
        return angle, stenosis
    except:
        return 0.0, 0.0

def prepare_data(real_path, fake_path):
    # Load files
    df_real = pd.read_csv(real_path)
    df_fake = pd.read_csv(fake_path)

    # Auto-Detect Column Names

    def get_case_col(df):
        for col in ['case_name', 'Case', 'case', 'ID']:
            if col in df.columns:
                return col
        raise KeyError(f"Could not find a case name column. Available columns: {df.columns.tolist()}")

    real_col = get_case_col(df_real)
    fake_col = get_case_col(df_fake)

    print(f"Success! Found '{real_col}' in Real data and '{fake_col}' in Fake data.")

    # Extract features
    real_features = np.array([parse_case_name(c) for c in df_real[real_col]])
    fake_features = np.array([parse_case_name(c) for c in df_fake[fake_col]])

    # Target FFR values
    real_ffr = df_real['FFR'].clip(lower=Config.FFR_MIN).values.reshape(-1, 1)
    fake_ffr = df_fake['FFR'].values.reshape(-1, 1)

    # Normalize
    scaler = MinMaxScaler()
    real_features_scaled = scaler.fit_transform(real_features)
    fake_features_scaled = scaler.transform(fake_features)

    return (torch.FloatTensor(real_features_scaled), torch.FloatTensor(real_ffr),
            torch.FloatTensor(fake_features_scaled), torch.FloatTensor(fake_ffr))

# 3. GAN Models

class Generator(nn.Module):
    def __init__(self):
        super(Generator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(Config.LATENT_DIM + Config.CONDITION_DIM, Config.HIDDEN_DIM),
            nn.ReLU(), nn.Linear(Config.HIDDEN_DIM, Config.HIDDEN_DIM),
            nn.ReLU(), nn.Linear(Config.HIDDEN_DIM, 1), nn.Sigmoid()
        )
    def forward(self, z, cond):
        return self.model(torch.cat([z, cond], dim=1))

class Discriminator(nn.Module):
    def __init__(self):
        super(Discriminator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(1 + Config.CONDITION_DIM, Config.HIDDEN_DIM),
            nn.LeakyReLU(0.2), nn.Linear(Config.HIDDEN_DIM, Config.HIDDEN_DIM),
            nn.LeakyReLU(0.2), nn.Linear(Config.HIDDEN_DIM, 1), nn.Sigmoid()
        )
    def forward(self, ffr, cond):
        return self.model(torch.cat([ffr, cond], dim=1))

# 4. MAIN EXECUTION

if __name__ == "__main__":
    REAL_FILE = 'ref_diameter_ffr_benchmark.csv'
    FAKE_FILE = 'biased_area_ffr_testset.csv'

    if os.path.exists(REAL_FILE) and os.path.exists(FAKE_FILE):
        # 1. Load and Preprocess
        r_feat, r_ffr, f_feat, f_ffr = prepare_data(REAL_FILE, FAKE_FILE)

        # 2. Setup GAN
        netG, netD = Generator().to(Config.DEVICE), Discriminator().to(Config.DEVICE)
        optG = optim.Adam(netG.parameters(), lr=Config.LR, betas=(Config.BETA1, 0.999))
        optD = optim.Adam(netD.parameters(), lr=Config.LR, betas=(Config.BETA1, 0.999))
        criterion = nn.BCELoss()

        # 3. Training Loop
        print("Starting Training...")
        loader = DataLoader(TensorDataset(r_feat, r_ffr), batch_size=Config.BATCH_SIZE, shuffle=True)
        for epoch in range(Config.EPOCHS):
            for cond, real_labels in loader:
                b_size = cond.size(0)
                cond, real_labels = cond.to(Config.DEVICE), real_labels.to(Config.DEVICE)

                # Train Discriminator
                netD.zero_grad()
                errD_real = criterion(netD(real_labels, cond), torch.ones(b_size, 1).to(Config.DEVICE))
                errD_real.backward()
                noise = torch.randn(b_size, Config.LATENT_DIM).to(Config.DEVICE)
                fake = netG(noise, cond)
                errD_fake = criterion(netD(fake.detach(), cond), torch.zeros(b_size, 1).to(Config.DEVICE))
                errD_fake.backward()
                optD.step()

                # Train Generator
                netG.zero_grad()
                errG = criterion(netD(fake, cond), torch.ones(b_size, 1).to(Config.DEVICE))
                errG.backward()
                optG.step()

            if epoch % 50 == 0:
                print(f"Epoch [{epoch}/{Config.EPOCHS}] | Loss_D: {errD_real+errD_fake:.4f} | Loss_G: {errG:.4f}")

        # 4. Final Plot
        netG.eval()
        with torch.no_grad():
            adj = netG(torch.randn(f_ffr.size(0), Config.LATENT_DIM).to(Config.DEVICE), f_feat.to(Config.DEVICE)).cpu().numpy()

        plt.figure(figsize=(12, 6))
        sns.kdeplot(r_ffr.numpy().flatten(), label='Real (Diameter)', fill=True, color='green')
        sns.kdeplot(f_ffr.numpy().flatten(), label='Biased (Area)', fill=True, color='red')
        sns.kdeplot(adj.flatten(), label='GAN Adjusted', fill=True, color='blue')
        plt.title("FFR Distribution Comparison - Final Results")
        plt.xlabel("FFR Value"); plt.ylabel("Density"); plt.legend(); plt.grid(alpha=0.3); plt.show()

        print(f"\nFinal Statistics:\nReal Mean: {r_ffr.mean():.4f}\nBiased Mean: {f_ffr.mean():.4f}\nAdjusted Mean: {adj.mean():.4f}")
    else:
        print(f"Error: Could not find files. Please ensure {REAL_FILE} and {FAKE_FILE} are uploaded.")